package uz.hesap.service.common.exception.handler;

public enum ErrorCode {
  API_ERROR_CODE(1000), // == // -------------------------------------------------------
  ALREADY_EXISTS_ERROR_CODE(1100), // ==
  USER_PHONE_EXIST(1100), // == // user exist with this number
  URL_NOT_FOUND(1201),
  USER_NOT_FOUND(1202),
  REQUIRED_FIELD_MISSED(1202),
  INVALID_EMAIL(1202),
  PASSWORD_LENGTH_ERROR(1203),
  WEAK_PASSWORD(1203),
  WRONG_CODE(1203),
  CATEGORY_NOT_FOUND(1203),
  PASSWORD_MISMATCH(1),
  NULL_POINTER_ERROR_CODE(1300), // ==
  UNEXPECTED_VALUE(1300), // ==
  UNSUPPORTED_OPERATION_ERROR_CODE(1400), // ==
  INVALID_ARGUMENT_ERROR_CODE(1500), // ==
  INVALID_CREDENTIALS_ERROR_CODE(1600), // ==
  INVALID_TOKEN_ERROR_CODE(1700),
  CACHE_IS_NOT_WORKING(23), // ==
  TOO_MANY_REQUEST(12), // ==
  INVALID_OPERATION_ERROR_CODE(1800),
  TIME_EXPIRED(1),
  NOT_FOUND_ERROR_CODE(1),
  LOCKING_CONFLICT_ERROR_CODE(2),
  RETRIEVE_FORBIDDEN_ERROR_CODE(2),
  SERVICE_UNAVAILABLE_ERROR_CODE(2),
  TIMEOUT_ERROR_CODE(2),
  UNAUTHORIZED_ERROR_CODE(2),
  UPDATE_FORBIDDEN_ERROR_CODE(2),
  USER_BLOCKED_ERROR_CODE(3),
  FILE_DOWNLOAD_ERROR_CODE(1),
  FILE_UPLOAD_ERROR_CODE(2),
  INTERNAL_ERROR_CODE(3),
  IO_EXCEPTION(3),
  MAX_UPLOAD_SIZE_EXCEEDED(3),
  INVALID_TYPE(3),
  BAD_REQUEST_CODE(3),
  JSON_PARSING_ERROR_CODE(3),
  FORBIDDEN_ERROR_CODE(3),
  LIST_FORBIDDEN_ERROR_CODE(3),
  CREATE_FORBIDDEN_ERROR_CODE(3),
  DELETE_FORBIDDEN_ERROR_CODE(3),
  INVALID_CODE(1901), // SMS verification code invalid
  CODE_EXPIRED(1902),
  SMS_SENDING_FAILED(12), // SMS verification code expired
  WITNESS_SIGN_REQUIRED(1903); // guvohlar imzolamaguncha taraf imzolay olmaydi
  public final int value;

  ErrorCode(int value) {
    this.value = value;
  }
}
